# Generated by Django 5.0.7 on 2024-08-31 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='Текст')),
                ('img', models.ImageField(blank=True, upload_to='photos/test_img/')),
                ('num_right', models.IntegerField(verbose_name='Кол-во правильных ответов')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Категория')),
                ('slug', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='Ответ')),
                ('right', models.BooleanField(default=False, verbose_name='Правильный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='testing_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testingcategory'),
        ),
        migrations.CreateModel(
            name='TestingPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt1', models.IntegerField(default=-1)),
                ('switch1', models.BooleanField(default=False)),
                ('attempt2', models.IntegerField(default=-1)),
                ('switch2', models.BooleanField(default=False)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testingcategory')),
            ],
        ),
    ]
